[package]
name = "rage"
authors = ["BraveeSnow"]
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rage"
path = "src/main.rs"

[lib]
name = "rage"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
once_cell = "1.18.0"
regex = "1.10.2"
